plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id 'maven-publish'
}

version = getSubprojectVersion(project)
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

dependencies {
	include(rootProject.project("banner-api"))
	include(rootProject.project("banner-transitive-access-wideners"))
	include(rootProject.project("banner-stackdeobf"))
	include(rootProject.project("banner-bukkit-manager"))
	include "net.kyori:adventure-api:4.14.0"
	include "net.kyori:adventure-key:4.14.0"
	include "net.kyori:adventure-text-minimessage:4.14.0"
	include "net.kyori:adventure-text-serializer-gson:4.14.0"
	include "net.kyori:adventure-text-serializer-json:4.14.0"
	include "net.kyori:adventure-text-serializer-legacy:4.14.0"
	include "net.kyori:adventure-text-serializer-plain:4.14.0"
	include "net.kyori:adventure-text-serializer-ansi:4.14.0"
	include "net.kyori:adventure-text-logger-slf4j:4.14.0"
	include "net.kyori:ansi:1.0.3"
	include "net.kyori:examination-api:1.3.0"
	include "net.kyori:examination-string:1.3.0"
}

moduleDependencies(project, [
		"banner-api",
		"banner-transitive-access-wideners"
])